### ISSUE TITLE
Fix method for centroid calculation

### ISSUE THREAD

**Issue by ryanfb** [ryanfb/pleiades-osm#2]
Currently, we just average the points, which will be incorrect for some shapes (see http://gis.stackexchange.com/questions/12120/calculate-midpoint-from-a-series-of-latitude-and-longitude-coordinates). We could use a gem like [`georuby`](https://github.com/nofxx/georuby) which provides centroid calculation.

**Comment by ryanfb** [comment]
Additionally, we should calculate the centroid for a closed Way (i.e. same beginning/end node), otherwise we should probably calculate the midpoint for a line (or just use the start/end points, or all points along the Way?).

**Comment by ryanfb** [comment]
It also turns out neither `georuby` nor `rgeo` actually implement centroid calculation.

For `georuby` I get:

```
./pleiades-osm.rb:28:in `centroid': wrong number of arguments (given 0, expected 1) (ArgumentError)
        from /Users/ryan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/georuby-2.5.2/lib/geo_ruby/simple_features/polygon.rb:19:in `method_missing'
```

If I try to use `georuby-ext` (which implements `#centroid`?), I get this error when trying to load the module:

```
/Users/ryan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.2/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method `parse_linear_ring' for class `GeoRuby::SimpleFeatures::EWKTParser' (NameError)
```

For `rgeo`, `#centroid` is simply programmed to raise an error saying it's unsupported:

```
/Users/ryan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rgeo-0.5.3/lib/rgeo/feature/surface.rb:63:in `centroid': Method Surface#centroid not defined. (RGeo::Error::UnsupportedOperation)
```

Maybe we should just copy `#calculate_centroid` from `geokit`? https://github.com/geokit/geokit/blob/master/lib/geokit/polygon.rb#L45-L68
